// staticData.js
export const campaigns = [
    {
      id: 'campaign_1',
      name: 'Campaign 1',
      status: 'Active',
      budget: '100.00 USD',
      cost: '50.00 USD',
      cpc: '0.50 USD',
      cpm: '10.00 USD',
      impressions: 5000,
      clicks: 100,
      ctr: '2.00%',
      conversions: 10,
      costPerConversion: '5.00 USD',
      conversionRate: '10.00%',
      results: 'Lead Generation',
      costPerResult: '5.00 USD',
      resultRate: '10.00%',
    },
    {
      id: 'campaign_2',
      name: 'Campaign 2',
      status: 'Paused',
      budget: '200.00 USD',
      cost: '80.00 USD',
      cpc: '0.40 USD',
      cpm: '8.00 USD',
      impressions: 10000,
      clicks: 200,
      ctr: '2.00%',
      conversions: 20,
      costPerConversion: '4.00 USD',
      conversionRate: '10.00%',
      results: 'Website Traffic',
      costPerResult: '4.00 USD',
      resultRate: '10.00%',
    },
  ];
  
  export const adGroups = [
    {
      id: 'adgroup_1',
      campaignId: 'campaign_1',
      name: 'Ad Group 1',
      status: 'Active',
      budget: '50.00 USD',
      cost: '25.00 USD',
      impressions: 2500,
      clicks: 50,
      ctr: '2.00%',
      results: 'Conversions',
    },
    {
      id: 'adgroup_2',
      campaignId: 'campaign_2',
      name: 'Ad Group 2',
      status: 'Paused',
      budget: '100.00 USD',
      cost: '40.00 USD',
      impressions: 5000,
      clicks: 100,
      ctr: '2.00%',
      results: 'Website Traffic',
    },
  ];
  
  export const ads = [
    {
      id: 'ad_1',
      adGroupId: 'adgroup_1',
      name: 'Ad 1',
      status: 'Active',
      impressions: 1250,
      clicks: 25,
      ctr: '2.00%',
      results: 'Leads',
      cost: '12.50 USD',
    },
    {
      id: 'ad_2',
      adGroupId: 'adgroup_2',
      name: 'Ad 2',
      status: 'Paused',
      impressions: 2500,
      clicks: 50,
      ctr: '2.00%',
      results: 'Website Visits',
      cost: '20.00 USD',
    },
  ];
  